name: horoflutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  gap: ^3.0.1
  get_storage: ^2.1.1
  intl: ^0.18.0
  async: ^2.11.0
  dio: ^5.4.0
  http_parser: ^4.0.2
  image_picker: ^1.0.5
  mime: ^1.0.4
  cached_network_image: ^3.3.0
  talker_logger: ^3.1.0
  flutter_svg: ^2.0.9
  dash_chat_2: ^0.0.19
  socket_io_client: ^2.0.3+1
  flutter_staggered_grid_view: ^0.7.0
  path_provider: ^2.1.1
  logger: ^2.0.2+1

dev_dependencies:
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/hozo/
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#0D1D23"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true
